src/compton.c
Setting it on the target buffer picture has no effect. Fix performance
problem when using xrender with virtual box.
Fixes #40
=> Set clip region on the target picture

compton.sample.conf, man/compton.1.asciidoc, src/common.h, src/compton.c, src/config_libconfig.c
When this option is enabled for a window type, shadow will be drawn in
areas that are obscure by the shape of the window.
Useful when the given window type has parts of the window transparent,
and you want to have shadows in those areas.
Fixes #45
=> Add per window type option full-shadow

compton.sample.conf, man/compton.1.asciidoc, src/common.h, src/compton.c, src/config_libconfig.c
Remove alpha_step, and support all 256 alpha values.
1 pixel pictures don't really use that many resources.
=> Support all alpha values

src/compton.c
Fix a divide by zero in delay time calculation.
Fixes #56
=> Don't delay update when refresh rate is not available

man/compton.1.asciidoc, src/compton.c, src/config.c, src/config_libconfig.c
This cause certain window types to be ignored in deciding whether the
screen should be redirected after being unredirected.
Fixes #58
=> Add wintype option `redir-ignore`.

man/compton.1.asciidoc, src/compton.c
As discussed in #25.
It turns out SGI_swap_control doesn't accept a swap interval of 0, so we need to use MESA_swap_control to disable it.
I've refactored and merged swc and mswc into one vsync method. It prefers MESA_swap_control when available and falls back to SGI_swap_control otherwise. The effects should remain the same in practice.
The old mswc option will print a warning and hand over to swc.
=> Improve swap-controlled vsync for mesa

man/compton.1.asciidoc, src/compiler.h, src/compton.c, src/config_libconfig.c, src/log.c, src/log.h, src/meson.build
It is not very pretty right now, but it will get better.
=> Add a logging framework

src/render.c, src/x.c, src/x.h
They should be useful for the refactored backends.
Renamed x_create_picture to x_create_picture_with_pictfmt.
=> Some new x helper functions

.circleci/config.yml, meson_options.txt, src/backend/backend.c, src/backend/backend.h, src/backend/backend_common.c, src/backend/backend_common.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/gl/glx.h, src/backend/meson.build, src/backend/xrender.c, src/common.h, src/compton.c, src/meson.build, src/win.c, src/win.h
This commit introduced a new, modular backend interface. The interface
is not very good, since I don't think I fully understand all the
requirements writing a backend have. But this is a good first step.
This commit also includes an initial xrender backend written using the
new interface, and some opengl backend related helper functions, which
are taken from the old opengl backend.
However, there is not integration with the core compton yet. compton
will still use the old backend code. This commit is here so we can get
the automated build test.
What is implemented in the new xrender backend:
* Windows with transparency
* Shadow
* Opacity
* Wallpaper (getting the root pixmap)
* Blur
Known problem with the xrender backend:
* It is slower
Things that still need to be figured out:
* What is …
=> First step of split backend into modules

src/config.c, src/config.h, src/options.c
Filling winopts with default values happened too early. It should happen
after command line options have been parsed, not after parsing the
config file.
Fixes #79
=> Fix wintypes options handling

src/backend/gl/gl_common.c, src/backend/xrender.c, src/common.h, src/config.c, src/config.h, src/config_libconfig.c, src/opengl.c, src/options.c, src/render.c, src/x.c, src/x.h
instead of keeping them as an array of xfixed.
=> Use struct conv for blur kernel as well

compton.sample.conf, man/compton.1.asciidoc, src/config.h, src/config_libconfig.c, src/dbus.c, src/opengl.c, src/options.c, src/render.c
=> Deprecate --glx-swap-method

README.md
This PR adds instruction on how to build compton on FreeBSD.
On FreeBSD, `ld` does not look into `/usr/local/lib` by default, which leaded to meson complaining about libev not being found, although it being installed and available in /usr/local/lib. The solution was to add `LDFLAGS="-L/usr/local/lib"` to the meson build command, and it locates the lib. That way we get Compton to compile and run on FreeBSD!
=> Add FreeBSD build instructions

README.md, meson.build, src/common.h, src/compton.c, src/dbus.c, src/meson.build, src/opengl.c, src/uthash_extra.h, src/win.c, src/win.h
Known problem: ID collision when a new window is created with the same
window ID as a destroyed window which is being faded out.
=> win: track windows with a hash table

meson.build
This will use --bindir value to install additional scripts into the same location
as compton binary (current behavior: hardcoded $prefix/bin).
Useful for custom installations and/or cross-compiling.
=> build: install scripts into bindir provided by meson

compton.desktop
Among other benefits, this will make [Lintian happy](https://lintian.debian.org/tags/desktop-entry-lacks-keywords-entry.html). The justification for this, is among other reasons, [searchability](https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords). Not to mention it just doesn't hurt.
=> added keywords to desktop entry

src/x.c
See [error log](https://github.com/yshui/compton/files/3720715/compton-n.100.1.log)
=> Unbreak build without OpenGL

picom.sample.conf, src/backend/backend.c, src/backend/backend.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/xrender/xrender.c, src/config.c, src/config.h, src/config_libconfig.c, src/dbus.c, src/options.c, src/utils.c, src/utils.h
Hey,
I have no idea if anybody is interested in this, so if You think it is useless for general case, just close this PR :wink:.
Anyway, I had this annoying problem, that when frequently switching between dark-themed windows and light-themed ones (especially when they take up most of the screen) there is no good screen brightness for both of them. Either dark-themed ones are too dark to comfortably look at them or light ones are too bright.
So I implemented this feature hoping to reduce that gap a bit by dimming windows depending on how bright they are.
Now initially I tried to implement this using mipmaps for brightness estimation, but there was significant CPU overhead on my computer (intel integrated GPU from 3rd gen processor, I also tested on 8th gen). What is more in order for them …
=> Dim bright windows

CONTRIBUTORS
That other quequotion is also me; I prefer the "full name" and bugmenot address.
=> Reduce quequotions in CONTRIBUTORS

src/compiler.h
DragonFly and OpenBSD neither support C11 threads nor define `__STDC_NO_THREADS__`. [According](https://codesearch.debian.net/search?q=__STDC_NO_THREADS__) to Debian `__STDC_NO_THREADS__` usage is uncommon, mostly limited to GNU libc.
https://sting.dragonflybsd.org/dports/logs/x11-wm___picom.log
=> Try to unbreak build on DragonFly

man/picom.1.asciidoc, src/config.c, src/config_libconfig.c, src/options.c
The manpage documents three options: `--blur-method`, `--blur-size` and `--blur-deviation`
This PR implements parsing of said options in the config file and on the command line.
=> Parse `--blur-*` options as documented in manpage

README.md
Without this package installed, meson will give `src/meson.build:27:1: ERROR: Dependency "x11-xcb" not found, tried pkgconfig and cmake`
=> Add libx11-xcb-dev as required dependency on Debian

README.md, src/config_libconfig.c, src/meson.build
This PR drops libxdg-basedir. 
I've implemented this in a way which avoids touching the existing code. It merely implements two functions to provide the same functionality provided by `libxdg-basedir` of which picom hardly used in the first place.
C isn't my forte so let me know if there are any issues. I also didn't try to adhere to the existing style as I'm sure there will be nitpicks about the code itself prior anyway. NOTE: I'm not freeing any memory as I believe picom does this itself afterwards(?). Let me know and I'll fix it.
Thanks
Closes #91
=> picom: Drop libxdg-basedir

dbus-examples/inverter.sh
List of changes:
- Removed unnecessary if statement and unnecessary /dev/null redirect on line 19
- Line 26 can use argless printf rather than echo -n
- Error verbose prints in red and to STDERR rather than to STDOUT
- (could change it back to print errors to STDOUT for compat)
- Textually replaced compton with picom where applicable
- Removed unnecessary semicolons after exit commands
- Replaced backticks with $()
I could've/likely missed a few things, however the script still seems runs the same for me.
=> Invert script optimizations 

.gitignore, src/backend/backend.c, src/event.c, src/picom.c, src/win.c, src/win.h, src/win_defs.h, tests/configs/issue314.conf, tests/run_tests.sh, tests/testcases/issue314_2.py, tests/testcases/issue314_3.py
The new experimental backends did not honor the `--blur-background-fixed` option. This implements handling of said option in the new backends.
If set to `false`, the (premultiplied) opacity of the blur-texture is dependent on the window opacity preventing awkward-looking blurred rectangles behind transparent windows especially with low `--inactive-opacity` values.
Example: https://imgur.com/a/sCDVqAI
In-depth discussion in https://github.com/tryone144/compton/issues/2
Stuff for further discussion:
The current (longtime) default of `false` did irritate some users who used a strong blur with `active-opacity` and `opacity-rule`: https://github.com/tryone144/compton/issues/25, https://github.com/tryone144/compton/issues/33
=> Experimental backends: fade/hide blur-texture for transparent windows

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h
Similar to the changes in #349 and as discussed over there, this PR sets the viewport to the maximum supported dimensions in the new OpenGL backend. In contrast to #349, the projection matrix in each shader has to be set only once when setting up the shader program and not for each draw call.
- Query maximum supported dimensions of `glViewport()` when initializing
so we don't have to worry about differently sized textures when
rendering (usually the same as the maximum supported texture size, but
dependend on the driver).
- Set projection matrix in all shaders at startup to queried viewport
dimensions. Allows using screen coordinates for all vertex positions
without having to keep track of framebuffer dimensions.
- Follow recommendations and set `glViewport()` to queried maximum …
=> gl_common: set `glViewport()` to maximum supported size

src/backend/gl/gl_common.c
Follow-up for #388
- Remove all calls to `glViewport()` in the new OpenGL backend. Setup viewport once at initialization to maximum supported dimensions.
- Fix previously incorrectly set viewport in `gl_average_texture_color()`. This used to be set to texture dimensions, but the corresponding projection matrix was set to root window/framebuffer dimensions. The resulting error was amplified by the changes introduced in #388. Now also uses global viewport dimensions.
Related: #247
=> gl_common: Set `glViewport()` once at startup

meson.build, meson_options.txt
This allows disabling installing several files that conflict with compton. By default they will still be installed unless `compton` is set to `true`.
This helps in case the system has both compton and picom installed.
=> meson: Allow building without compton compat.

man/meson.build
Respects the default `mandir` meson option. There will be no change in behavior unless `mandir` is set. Not all distros use `share/man`.
=> meson: Respect mandir.

src/meson.build
https://sting.dragonflybsd.org/dports/logs/x11-wm___picom.log
https://marc.info/?l=openbsd-ports&m=159060985008515 (patch-src_meson_build)
=> Unbreak build on DragonFly and OpenBSD

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/xrender/xrender.c
Use correct wrap/repeat setting for blur textures to prevent darkening around the screen borders. This occurs due to sampling outside of the texture, especially noticeable with larger blur radii.
The required changes to the fragment shader allowed for further improvements by utilizing the linear interpolation hardware in a GPU in the glx backend.
<details>
<summary>Old behavior:</summary>
</details>
<details>
<summary>New behavior:</summary>
</details>
1. Use correct `REPEAT` mode `PAD` when creating blur pictures in the xrender backend to pad the 
image with edge pixels.
2. Use correct `WRAP` mode `CLAMP_TO_EDGE` when creating blur textures in the glx backend to clamp sampling to the edge pixels. Required changes to the fragment shader:
- Use `texture2D()` instead of `texelFetch()`, as …
=> Better blur texture sampling (in experimental backends)

man/picom.1.asciidoc, picom.sample.conf, src/backend/backend.h, src/backend/backend_common.c, src/backend/backend_common.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/xrender/xrender.c, src/config.c, src/config.h, src/config_libconfig.c, src/options.c, src/picom.c
This PR implements the dual-filter kawase blur algorithm as [found in KWin](https://kwin.kde.narkive.com/aSqRYYw7/d9848-updated-the-blur-method-to-use-the-more-efficient-dual-kawase-blur-algorithm).
Usable with `--blur-method dual_kawase --blur-strength 7`.
**~~This is currently work-in-progress and open for comments. DO NOT MERGE.~~**
Should be ready to merge now.
Previous discussion: https://github.com/yshui/picom/issues/32
See also: https://github.com/yshui/picom/pull/361
EDIT: Sorry, clicked submit too fast...
=> dual-kawase blur algorithm for new OpenGL backend

picom.sample.conf
This replaces single quotes for double quotes in the configuration
comments that refer to strings.
This was misleading since someone could took that comment as a valid
config entry, which is not.  One notable example was `backend = 'glx'`
which is not accepted by libconfig.
This also adds `;` for each default config values for consistency.
=> Do not use single quotes in the example config

src/log.c
Fixes [CodeQL warning](https://github.com/yshui/picom/security/code-scanning/1) about use of non-thread-safe `localtime()`.
=> Fix CodeQL warning

src/backend/gl/gl_common.c
Parentheses are required around macro argument containing braced initializer list.
memcpy(3) is a macro when using e.g. -D_FORTIFY_SOURCE=2.
=> Fix the build when memcpy is defined as a macro.

bin/picom-trans, man/picom-trans.1.asciidoc
* Add new option `-h, --help` to `picom-trans` to print a help message with all supported options (see #513). Updated the manpage to reflect all supported options as well.
* Add new action `-t, --toggle` to `picom-trans` to toggle between set opacity and delete opacity — i.e. unset (see #472).
=> Add `--help` and `--toggle` options to `picom-trans`

.clang-tidy, src/atom.c, src/atom.h, src/c2.c, src/compiler.h, src/picom.c, src/render.c, src/win.c, src/x.c, src/x.h
Of course, we still use GLX, so we can't completely remove Xlib yet. But
this removes all Xlib uses outside of the backends.
=> x: remove the last bit of Xlib dependency

src/c2.c, src/options.c, src/picom.c
- Fix non-critical memory-leak in `picom.c` and `options.c` where we don't free all allocated memory before dieing.
- Explicitly allocate new branch in `c2.c` to silence false-positive memory-leak.
=> Fix/silence memory errors reported by `scan-build`.

src/win.c, tests/configs/issue394.conf, tests/run_tests.sh, tests/testcases/common.py, tests/testcases/issue394.py
This should fix various crashes where the shadow images created/updated in-time (both legacy and experimental backends).
<details>
<summary>EDIT: Fix has already been merged outside of this PR</summary>
First of all, fixes https://github.com/yshui/picom/issues/465 by partially reverting https://github.com/yshui/picom/commit/32754b0 (this seems to be the "benefit to keep them separate").
Shadow images might be updated/invalidated (via the `SHADOW_STALE` flag) depending on the focus-state (in `recheck_focus()`). We therefore have to refresh/create shadow images after that. Handling of the `MAPPED` flag however still has to be done before focus checking, otherwise we introduce a single frame lag for windows that are to be mapped and have rules depending on the focus-state.
@yshui I hope the …
=> Fix crashes when trying to (re-)create shadows for destroyed windows

src/picom.c, src/win.c
hello there,
I know, this is some hardcore nitpicking, so feel free to ignore it.
While building the latest release I got annoyed by the warnings and decided to fix them.  Turns out, 99% of the warnings I get are due to uthash' macro (missing fallthrough annotation in particular), so this pr fixes only the remaining 1%: three wrong format string for uint64_t and a missing brace (in clang opinion).  Now, if I build with -Wno-implicit-fallthrough there aren't warnings, yeee!
Regarding the format string: on my system uint64_t is long long unsigned int, but maybe that's not the case everywhere? In doubt, I used the PRI macros from inttypes.h
edit: sorry if I messed up when creating the pr.  Now it should be as intended.
=> [nitpicking] silencing some warnings

src/event.c, src/picom.c, src/win.c, src/win.h, tests/run_tests.sh, tests/testcases/issue525.py, tests/testcases/redirect_when_unmapped_window_has_shadow.py
Make unmapped window events work mostly like a mapped window, except
flags set on unmapped windows aren't processed until the window is
mapped.
Hopefully this unifies some of the code paths and reduce corner cases.
Should fix #525
=> win: rework how events for unmapped windows are handled

man/picom.1.asciidoc, picom.sample.conf, src/config.c, src/config.h, src/config_libconfig.c, src/options.c, src/picom.c, src/render.c, src/render.h, src/win.c, src/win.h
=> Rounded corners for legacy xrender backend

src/c2.c, src/config.c, src/dbus.c, src/string_utils.h
Per POSIX, "The c argument is an int, the value of which the application shall ensure is a character representable as an unsigned char or equal to the value of the macro EOF. If the argument has any other value, the behavior is undefined."
https://pubs.opengroup.org/onlinepubs/009604499/functions/isspace.html
=> Cast argument to ctype functions to unsigned char

compton.desktop, picom-dbus.desktop, picom.desktop
This set "NoDisplay=true" in `picom.desktop`, `compton.desktop` and `picom-dbus.desktop`.
This will hide them by default on most "application menus"  which makes sense since in most case they should not be launched manually anyway.
This was actually proposed back in the [original issue](https://github.com/chjj/compton/issues/97) but for some reason it was not added to the commit.
[Desktop Entry Specification#Recognized desktop entry keys](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html)
=> set .desktop files to "NoDisplay=true"

man/picom.1.asciidoc, src/c2.c, src/x.c, src/x.h
~~Change the default~~Add special index `[*]` in window-rule matching to check against any value if the property in question is an array ~~instead of only checking the first value if no index is provided~~. See the discussion in #512 for why this makes more sense:
```
opacity-rule = [ "0:_NET_WM_STATE@[*]:32a *= '_NET_WM_STATE_HIDDEN'" ];
```
instead of
```
opacity-rule = [
"0:_NET_WM_STATE@[0]:32a *= '_NET_WM_STATE_HIDDEN'",
"0:_NET_WM_STATE@[1]:32a *= '_NET_WM_STATE_HIDDEN'",
"0:_NET_WM_STATE@[2]:32a *= '_NET_WM_STATE_HIDDEN'",
"0:_NET_WM_STATE@[3]:32a *= '_NET_WM_STATE_HIDDEN'",
"0:_NET_WM_STATE@[4]:32a *= '_NET_WM_STATE_HIDDEN'",
];
```
=> c2: Perform matching against "all" property values with special index `[*]`

src/opengl.c, src/opengl.h, src/options.c, src/render.c, src/win.h
Authored-by: bhagwan <bhagwan@disroot.org>
Authored-by: Samuel Hand <samuel.d.hand@gmail.com>
=> Rounded corners for legacy glx backend

.circleci/config.yml
While investigating why the docs where not being build in NixOS (see https://github.com/NixOS/nixpkgs/pull/108530), I discovered that the flag to build docs changed, but there is one place in the code that still used the old flag.
This was renamed in commit 3f2a671, but I think it was simply forgotten in CI.
=> circleci: rename "-Dbuild_docs" -> "-Dwith_docs"

README.md
I just spent some time looking up all the package names required to build picom on Fedora. This would add this to the README.
To confirm that this is enough for building (at least on Fedora 33), create a `Dockerfile` with the following:
```Dockerfile
FROM fedora:33
WORKDIR /picom
RUN dnf -y install \
asciidoc \
dbus-devel \
gcc \
git \
libconfig-devel \
libdrm-devel \
libev-devel \
libX11-devel \
libX11-xcb \
libXext-devel \
libxcb-devel \
mesa-libGL-devel \
meson \
pcre-devel \
pixman-devel \
uthash-devel \
xcb-util-image-devel \
xcb-util-renderutil-devel \
xorg-x11-proto-devel
```
and run:
```sh
docker build -t picom-build . && docker run --rm -v $PWD/out:/out:Z picom-build bash -c "\
git clone https://github.com/yshui/picom/ /picom && \
git submodule update --init --recursive && \ …
```
=> Add packages needed for building on Fedora to README.

picom.desktop
=> Support Menu Icon

src/opengl.c, src/opengl.h, src/render.c, src/win.c, src/win.h
=> Rounded border

src/backend/xrender/xrender.c
When using `frame-opacity != 1` with the experimental xrender backend the frame does not become transparent if the window has a 24-bit visual (see https://github.com/yshui/picom/issues/342#issuecomment-602266312).
Therefore, force a 32-bit ARGB visual when cloning pixmaps for `IMAGE_OP_APPLY_ALPHA` in the xrender backend.
fixes: #342
=> Fix non-transparent frames for opaque windows in experimental xrender backend

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h
The (proprietary) NVIDIA driver apparently does not support attaching textures that are bound to a glx pixmap to a framebuffer object. Doing so fails the framebuffer-completeness test with `GL_FRAMEBUFFER_UNSUPPORTED`.
AMD and Intel seems to not be affected: https://github.com/yshui/picom/issues/647#issuecomment-867746911, https://github.com/yshui/picom/issues/647#issuecomment-867966401
Partially reverts `gl_image_decouple()` in 2a60836a9bc30d92b4adb46d5f48684a5d2f1ecb:
Instead of binding the source texture to a framebuffer and then copying with `glTexImage2D()`, bind the destination texture to the framebuffer and copy the source texture with a simple quad-rending.
Also includes more detailed error messages should a framebuffer not be complete.
fixes: #645, #647
=> nvidia driver does not support attaching pixmap texture to fbo

src/picom.c
If the user has no access to the GPU, initialization of the GLX context fails. In the legacy backend, this occurs BEFORE the session has been successfully initialized, triggering an XError.
At this point we cannot meaningfully filter XErrors as the session hasn't been initialized yet. Trying to filter triggers a SEGFAULT in `discard_ignore()`.
So for as long as the session is not initialized we do not try to filter out any errors.
@yshui are you okay with this solution or would you like the `!= NULL` check to be in `should_ignore()` instead?
=> Do not try to ignore xerrors before session is initialized

src/event.c, src/win.c
Fix incorrect calculation of window frame region (based on `_NET_FRAME_EXTENTS`) that caused the frame-opacity to be applied only to the top and left frame borders. Opaque windows with blurred transparent frames, would show a blurred outline on the bottom and right.
As mentioned in https://github.com/yshui/picom/commit/fb3305fb9bf7801f0b8608cd92f90d8b548688a8, the window geometry does not include the border width. However, `_NET_FRAME_EXTENTS` seem to include the border width.
So to correctly get the frame regions we subtract the reported frame extents from our window *including* the border width — conveniently already available in `widthb` and `heightb` (compare [frame rendering logic](https://github.com/yshui/picom/blob/5388ba0946bb325b343e04c4dfc66ca05d4d1466/src/render.c#L477-L538) in …
=> Fix incorrect frame region in new backends

src/backend/driver.c, src/backend/gl/glx.c
This essentially concludes my issue #592, implementing the original change mentioned in my first post (instead of the other, later implementations I tried, which in the time since, I've decided they were only marginal improvements, with testing ultimately being inconclusive - at a cost of (personally) unacceptable amount of changes to the code/code separation.*)
_*I'll mention more about the "inconclusive testing" later, for anyone reading this and thinking the ideas mentioned in #592 have some merit. Which I do still think they have, but the cost of implementation is high. High enough that I no longer think it is practical. A hardware upgrade, honestly, might be more practical (compared to more consistent 59-60Hz if fixed - as the smoothness issue with picom really only affects 60Hz and …
=> Set GL_MaxFramesAllowed=1 instead of GL_YIELD=usleep

man/picom.1.asciidoc, picom.sample.conf, src/backend/backend.c, src/config.c, src/config.h, src/config_libconfig.c, src/options.c, src/picom.c, src/render.c, src/win.c, src/win.h
Added the new `shadow-crop-window` configuration option and `crop-shadow` wintype option. These allow the user to select windows to crop from the shadow region of other windows, i.e. don't paint shadows on top of them.
This should provide a more useful and user friendly alternative to the deprecated `shadow-exclude-reg` option.
See https://github.com/yshui/picom/issues/494 and https://github.com/yshui/picom/pull/582#issuecomment-809261483.
---
The name of this new option is up for debate. My rationale behind not calling it `shadow-exclude-window` was to avoid confusion with the similarly named `shadow-exclude` option that disables the shadow that a window casts. In contrast, the new option prevents shadows from being cast onto the target window.
I am not a native speaker, so if *crop* …
=> Add `clip-shadow-above` configuration and wintype option

bin/picom-trans
I have re-written picom-trans to be better understandable. Also added comments.
=> Rewrite picom-trans

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h
Blur-texture sampling has been changed to `CLAMP_TO_EDGE` in commit 4b0ff37b36c58455a47a9044bd2b7e7c2cc3bc73 and to using the buffer textures at screen position instead of texture origin in commit 89c18afac65c18cd84268d946866320ab7b9f440.
When using the above approach, expanding the buffer textures by the same amount as the damage region is not needed anymore, as we cannot render more than the screen region anyways. Having larger-than-screen buffer textures might lead to a slight darkening at the upper and right edges since we don't necessarily trigger the `CLAMP_TO_EDGE` condition in the intermediate steps. This becomes apparent when using dual-kawase at large blur-strengths with light backgrounds.
These changes do not affect the general approach of rendering a larger-than-window region …
=> Experimental GL backend: Do not use larger-than-screen textures for blur buffers

src/backend/backend_common.c
This fixes the ugly black shadow that I was thinking was related to overlapping shadows noted here:
https://github.com/yshui/picom/issues/664#issuecomment-912931978
but in reality it was simply caused by shadow opacity not being added to the shadows in case windows were smaller than the radius of the shadow.
=> Fixed ugly dark shadows in case of smaller window than shadow radius.

picom.sample.conf
See https://github.com/yshui/picom/issues/534
This got me, for whatever reason that issue isn't prioritized very highly by google so it took a while to figure out why this was happening (IE I had to start by seeing if there was an issue in I3 + XFCE, then narrow it down to see if there was an issue in EWMH, then finally realized there was an issue here)
Leaving it as `false` in the sample conf seems to make sense as it matches what most WM's consider `active` and it's such a noticeable setting.
Alternatively, we could just add documentation of this setting to the README to make it more discoverable while leaving the sample conf as is :shrug:
=> Use default `detect-client-leader` in sample conf

src/utils.h
Some versions of Android libc do not have timespec_get(), use
clock_realtime() instead on Android.
Signed-off-by: Rafael Kitover <rkitover@gmail.com>
=> Fix lack of timespec_get() on Android.

src/c2.c
Awesome window manager uses properties that have dots (`.`) in their name, like `awful.client.property.floating(CARDINAL) = 1`. This caused error like `Pattern "awful.client.property.floating@:c = 1" pos 5: Target type cannot be determined.` So why not allow it in target syntax of conditions.
I needed this myself, so I just made a quick edit and did not have time to dive too deep into this project.
=> allow dots (.) in condition targets

src/backend/backend.c, src/backend/backend.h, src/backend/backend_common.c, src/backend/backend_common.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/xrender/xrender.c, src/options.c, src/x.c, src/x.h
This pull request add basic rounded corner for the new glx and xrender backends.
=> New backend rounded corner, part 1

src/backend/backend.c, src/backend/backend_common.c, src/c2.c, src/common.h, src/picom.c, src/win.c, src/win.h, tests/testcases/basic.py, tests/testcases/clear_shadow_unredirected.py, tests/testcases/issue239.py, tests/testcases/issue239_2.py, tests/testcases/issue239_3.py, tests/testcases/issue239_3_norefresh.py, tests/testcases/issue314.py, tests/testcases/issue314_2.py, tests/testcases/issue314_3.py, tests/testcases/issue357.py, tests/testcases/issue394.py, tests/testcases/issue465.py, tests/testcases/issue525.py, tests/testcases/redirect_when_unmapped_window_has_shadow.py
When running the tests on 32 bit architectures, `picom` was segfaulting because (I think) of using `%ld` in printf-style format strings when passing 64 bit numbers. I used `PRIu64` for these cases and fixed the other warnings that showed up when compiling on 32 bits.
FYI `long long` is 64 bits in size on both 32 bit and 64 bit architectures: https://logncomplexity.wordpress.com/2016/01/20/integer-sizes-in-c-on-32-bit-and-64-bit-linux/.
I also changed all the `tests/testcases/*` files to use `python3` in the shebang since all of the python files are compatible with python 3. (The command I used to do that is: `find tests/testcases/ -type f -exec sed -i 's|env python$|env python3|g' {} \;`)
=> Fix segfault on 32 bit architectures when using debug logging

src/backend/backend.c, src/backend/backend.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/gl/glx.h
Use GL_ARB_robustness extension to detect GPU reset, and reset picom.
This is only marginally helpful. Yes, with this picom indeed regain normal function after GPU resets, but since X doesn't handle reset properly, all the windows have garbled content. Maybe in the future we can display some kind of warnings/instructions to the user if a reset happens.
=> Detect and handle GPU reset

.circleci/config.yml, src/c2.c, src/compiler.h, src/utils.h, tests/configs/parsing_test.conf
GCC warns about a use after free, because a pointer is used in pointer
comparison after it was freed. This particular case is completely safe,
but GCC warns anyway.
Move the free after the comparison requires me duplicating the free a
couple of times, so instead I made use of the cleanup attribute to auto
free the pointer when it goes out of scope.
=> c2: silence a compiler warning

.circleci/config.yml, README.md, man/picom.1.asciidoc, src/config.c, src/config.h, src/options.c, src/picom.c, src/win.c, tests/run_one_test.sh
=> Make experimental backends the new default

man/picom.1.asciidoc, picom.sample.conf, src/config.h, src/config_libconfig.c, src/options.c, src/picom.c, src/win.c, src/win.h
As described in #663, using `transparent-clipping` does not interact well with screenshooting tools with window selection indicators. The screenshooting tool draws a mostly transparent full-screen window to highlight the window selection, which means that with `transparent-clipping` enabled only the root window and the window selection indicator are visible.
This PR adds an `transparent-clipping-exclude` config entry, which allows the user to specify windows that should bypass the `transparent-clipping = true` setting. The transparent elements of such windows will show any windows below, not just the root window.
Tested with `slop`, `xfce4-screenshooter` and `st` (I don't see much point in using this with a terminal emulator window but it works).
=> Add transparent-clipping-exclude config option to improve usability with screenshooting tools
