yshui/picom

Makefile, src/common.h, src/compton.c, src/compton.h, src/win.c, src/x.c, src/xrescheck.h
Hi again,
this PR contains
- Composite and SHAPE extension
- Conversion of `XCreatePixmap` and `XFreePixmap`
- some improvement to error handling
- actually handling asynchronous errors (again)
By the way, feel free to tell me to stop doing these if it causes problems for you with the pixman conversion.
=> More conversion to XCB

src/compton.c
When using DRI2, Mesa uses XESetWireToEvent to hook into Xlib's event
handling loop, so it can get notified when certain DRI2 event happens,
which is crucial to the normal functioning of GLX.
When xcb is owning the event queue (meaning libxcb is doing all the
event handling), those functions registered by Mesa will never be
called, thus GLX will malfunction, leading to screen flickers or visual
artifacts.
This commit uses a hack from Qt to manually call those functions in
compton.
=> Workaround the incompatibility between DRI2 and xcb

src/c2.c, src/common.h, src/compton.c, src/compton.h, src/config.c, src/config_libconfig.c, src/dbus.c, src/kernel.c, src/log.c, src/log.h, src/meson.build, src/opengl.c, src/opengl.h, src/region.h, src/render.c, src/string_utils.h, src/utils.c, src/utils.h, src/vsync.c, src/win.c, src/x.c, src/xrescheck.c
And improve some of the log messages. Like, when compton exits because
of unsupported options, explain which options are causing compton to
quit.
=> Convert print_errf in win.c and compton.c

src/backend/backend.c, src/backend/backend_common.c, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/xrender.c, src/c2.c, src/compton.c, src/compton.h, src/compton.modulemap, src/config.c, src/config.h, src/config_libconfig.c, src/dbus.c, src/diagnostic.c, src/log.c, src/opengl.c, src/opengl.h, src/options.c, src/region.h, src/render.c, src/render.h, src/utils.c, src/vsync.c, src/win.c, src/win.h, src/x.c
Expand the modulemap to cover some of the system headers too.
=> Even more includes

src/backend/gl/glx.c, src/common.h, src/compton.c, src/opengl.c, src/render.c, src/render.h
Could be useful for new backends.
=> Make damage tracking not glx specific

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/meson.build, src/log.c, src/opengl.c, src/opengl.h
=> Reuse some code from the new gl backend

src/backend/backend_common.c, src/backend/xrender.c, src/compton.c, src/compton.h, src/render.c, src/win.c, src/x.c, src/x.h
Replace session_t parameter with xcb_connection_t if that's the only
thing needed.
=> Most of the x_* functions don't need session_t

.circleci/config.yml, man/compton.1.asciidoc, meson_options.txt, src/backend/backend.h, src/backend/meson.build, src/compton.c, src/compton.h, src/config.h, src/options.c, src/win.c
Goal is to make new and old backends co-exist in compton.
Was: #39 
Follow up: [`remove-old-backends`](https://github.com/yshui/compton/tree/remove-old-backends)
=> Integrate new backends

src/backend/backend.c, src/backend/backend.h, src/backend/backend_common.c, src/backend/backend_common.h, src/backend/gl/glx.c, src/backend/gl/glx.h, src/backend/xrender.c, src/common.h, src/compton.c, src/render.c, src/win.c, src/win.h, src/x.c, src/x.h
Move more logic out of the backend. The backends are now more agnostic
to what happens in compton.
=> new_backend: New interface

src/backend/backend.c, src/backend/backend.h, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/xrender/xrender.c, src/types.h
Slight change to the backend_operations::fill interface.
=> new backend: glx: implement IMAGE_OP_APPLY_ALPHA

src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/xrender/xrender.c, src/common.h, src/compton.c, src/config.c, src/config.h, src/config_libconfig.c, src/opengl.c, src/opengl.h, src/options.c, src/render.c, src/x.c, src/x.h
=> Lift the MAX_BLUR_PASS limit

.circleci/config.yml, tests/run_tests.sh
=> Run test cases in CI

src/backend/driver.c, src/compton.c, src/win.c
(should probably be cherry-picked to stable as well)
=> fix a few memory leaks reported by valgrind

dbus-examples/inverter.sh
Additional rebranding to be done here, but first of all make this work.
=> inverter.sh: pgrep picom

picom.sample.conf
i tried to include all the examples given in the mainpage and sorted them a bit around.
im not sure on all the default values given, maybe you could double check.
=> improved sample conf to cover all options present in the manpage

src/backend/gl/gl_common.c
=> gl_common: unify gd definition

.github/workflows/coding-style.yml
=> github action: check coding style of commits

man/picom.1.asciidoc, picom.sample.conf, src/config.c, src/config.h, src/config_libconfig.c
This PR add hex string for shadow instead of just rgb values
#257
=> add shadow-hex option

.github/workflows/codeql-analysis.yml
=> github: codeql: only install dependencies for cpp analysis

src/event.c, src/win.c, src/win.h, src/win_defs.h
Move handling window property changes into the X critical section.
=> event: delayed handling of window property changes

src/event.c, src/win.c, src/win.h, src/win_defs.h
Part of the configure notify handling which requires querying the X
server, has been moved into the X critical section.
There is more to come.
=> More delayed event handlings

.github/issue_template.md
Hello,
I want to suggest some minor changes to the issue template:
- `compton` should be completely gone by now
- I added spoiler tags for both the diagnostics and configuration file so that the issues don't look as crowded
Feel free to tell your thoughts or just delete the PR if this is not needed!
=> Minor fixes to the issue template

bin/picom-trans
=> Improve POSIX-compatibility of picom-trans

src/backend/backend.c
=> Backend improvements

bin/picom-trans
https://github.com/yshui/picom/pull/634#issuecomment-885737583
=> picom-trans: Added SPDX-License-Identifier

man/picom.1.asciidoc, picom.sample.conf, src/common.h, src/config.c, src/config.h, src/config_libconfig.c, src/dbus.c, src/options.c, src/picom.c, src/picom.h
=> Deprecation chore

picom.sample.conf, src/config_libconfig.c, src/dbus.c
=> DBus improvments 

man/picom.1.asciidoc
=> Made a typo fix in the man docs

src/backend/backend.c, src/backend/backend.h, src/backend/dummy/dummy.c, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/xrender/xrender.c, src/utils.h, src/win.c, src/win.h
=> Shadow behind rounded corners

src/backend/backend.c, src/backend/backend.h, src/backend/dummy/dummy.c, src/backend/gl/gl_common.c, src/backend/gl/gl_common.h, src/backend/gl/glx.c, src/backend/xrender/xrender.c, src/utils.h, src/win.c, src/win.h
=> Fix blur behind rounded corner windows.
